### ISSUE TITLE
Sciunit in Flinc Failing Install on Chamelon

### ISSUE THREAD

**Issue by sranasir** [depaul-dice/Flinc#1]
This issue is specific to Chameleon only. When installing Sciunit shipped as part of FLINC, the following error is received:

>       make: *** [Makefile:91: all] Error 2
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-req-build-u2p2o4lj/setup.py", line 33, in <module>
>           setup(
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 103, in setup
>           return distutils.core.setup(**attrs)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/core.py", line 185, in setup
>           return run_commands(dist)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
>           dist.run_commands()
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
>           self.run_command(cmd)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/dist.py", line 963, in run_command
>           super().run_command(command)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/usr/local/lib/python3.9/dist-packages/wheel/bdist_wheel.py", line 368, in run
>           self.run_command("build")
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/dist.py", line 963, in run_command
>           super().run_command(command)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/command/build.py", line 131, in run
>           self.run_command(cmd_name)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
>           self.distribution.run_command(command)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/dist.py", line 963, in run_command
>           super().run_command(command)
>         File "/usr/local/lib/python3.9/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
>           cmd_obj.run()
>         File "/tmp/pip-req-build-u2p2o4lj/setup.py", line 17, in run
>           subprocess.check_call(['make', '-j4'])
>         File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['make', '-j4']' returned non-zero exit status 2.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for sciunit2

This issue arises both with Python 3.9 and 3.10. The Sciunit installation on CyberGIS Jupyter for Water takes place fine.
This issue is not blocking and urgent but needs to be looked at soon.

**Comment by sranasir** [comment]
This issue was arising due to this issue https://github.com/depaul-dice/sciunit/issues/38. It has been resolved after the commits https://github.com/depaul-dice/sciunit-dedup/commit/64f496f598a4dd499c09428324110d5f4c7a1b83 and https://github.com/depaul-dice/sciunit/commit/2990cf5adb0b0fc4420def7504a0ad5b79b97b8b.
